#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH="\\\"\\\""


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

# ── Single-flight queue — CUSTOM, not part of the stock Gradle wrapper ──────────────
# This machine cannot run two `./gradlew` invocations at once without resource
# exhaustion (each daemon can reserve gigabytes of heap; two full JVMs contending for
# the same cores stalls both). Every invocation — from any terminal, any agent
# session — serializes on a single machine-wide lock instead of piling on: the second
# one waits for the first to finish rather than starting concurrently.
#
# `mkdir` is used (not `flock`) because `flock(1)` is a Linux util-linux tool that
# macOS does not ship. `mkdir` on a not-yet-existing path is atomic on every POSIX
# filesystem, so it doubles as a portable lock: at most one invocation can create the
# directory, so at most one holds the lock at a time.
#
# The lock path is a fixed literal (not derived from $APP_HOME), so every checkout of
# this project on this machine — including any .claude/worktrees/* — shares the SAME
# queue, since the resource contention this guards against is machine-wide, not
# per-checkout.
#
# NOTE for maintainers: this block (and the change from `exec` to a plain foreground
# call below it) is NOT regenerated by `gradle wrapper` — running that task to bump
# the Gradle version overwrites this whole file back to the stock wrapper and silently
# drops the queue. Re-apply this block after any such regeneration.
GRADLEW_LOCK_DIR="/tmp/tahfeezkmp1-gradlew.lock"
GRADLEW_LOCK_PID_FILE="$GRADLEW_LOCK_DIR/pid"
GRADLEW_LOCK_HELD=""

gradlew_release_lock() {
    if [ -n "$GRADLEW_LOCK_HELD" ]; then
        rm -rf "$GRADLEW_LOCK_DIR"
        GRADLEW_LOCK_HELD=""
    fi
}
# Separate handlers, not one `trap ... EXIT INT TERM`: a signal caught while still inside the
# `mkdir` wait loop below must actually terminate the script, or the loop just keeps spinning —
# releasing a lock that was never held is a no-op, and returning from the trap hands control right
# back to `while`. So INT/TERM release the lock (if held) and exit explicitly; EXIT alone covers
# every other way the script ends (normal return, `die`, the explicit `exit` below), including the
# exit calls made here, which is safe since gradlew_release_lock() is idempotent.
trap gradlew_release_lock EXIT
trap 'gradlew_release_lock; exit 130' INT
trap 'gradlew_release_lock; exit 143' TERM

gradlew_acquire_lock() {
    waited=0
    announced=""
    while ! mkdir "$GRADLEW_LOCK_DIR" 2>/dev/null; do
        # Stale-lock recovery: the PID that created the lock dir is no longer alive
        # (e.g. the machine restarted, or the holder was killed without unwinding its
        # trap) — reclaim the lock instead of waiting forever for a process that will
        # never finish.
        if [ -f "$GRADLEW_LOCK_PID_FILE" ]; then
            holder_pid=$(cat "$GRADLEW_LOCK_PID_FILE" 2>/dev/null)
            if [ -n "$holder_pid" ] && ! kill -0 "$holder_pid" 2>/dev/null; then
                echo "gradlew: reclaiming stale lock left by dead process $holder_pid" >&2
                rm -rf "$GRADLEW_LOCK_DIR"
                continue
            fi
        fi
        if [ -z "$announced" ]; then
            echo "gradlew: another build is running on this machine — waiting for it to finish ($GRADLEW_LOCK_DIR)..." >&2
            announced=1
        elif [ $((waited % 30)) -eq 0 ]; then
            echo "gradlew: still waiting (${waited}s)..." >&2
        fi
        sleep 2
        waited=$((waited + 2))
    done
    echo $$ > "$GRADLEW_LOCK_PID_FILE"
    GRADLEW_LOCK_HELD=1
}

gradlew_acquire_lock
# ── end single-flight queue ─────────────────────────────────────────────────────────

# Not `exec`: `exec` replaces this process image, so a trap registered above would
# never run afterwards and the lock would never be released. A plain foreground call
# keeps this shell alive just long enough to release the lock once Gradle exits, then
# exits with the same code Gradle did.
"$JAVACMD" "$@"
GRADLEW_EXIT_CODE=$?
gradlew_release_lock
exit "$GRADLEW_EXIT_CODE"
